#!/usr/bin/env python3
"""Machine-derived dataset quality report. Ingests the real data into a throwaway DB,
normalizes, validates, and emits reproducible statistics to docs/dataset-quality-metrics.md
+ stdout JSON. No hand-typed numbers.

Usage: python scripts/data_quality_report.py
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "backend"))

_tmp = tempfile.NamedTemporaryFile(suffix=".db", delete=False)
_tmp.close()
os.environ["DATABASE_URL"] = f"sqlite:///{_tmp.name}"
os.environ.setdefault("RULESET_PATH", str(REPO / "backend" / "seed" / "validation_rules.json"))

import app.models  # noqa: E402,F401
from app.core.db import Base, SessionLocal, engine  # noqa: E402
from app.ingestion.service import ingest_csv, ingest_servicer_csv  # noqa: E402
from app.models.loan import Loan  # noqa: E402
from app.models.raw_record import RawRecord  # noqa: E402
from app.models.validation import LoanException  # noqa: E402
from app.validation.service import run_validation  # noqa: E402
from sqlalchemy import func, select  # noqa: E402

DATA = REPO / "data" / "raw"


def build() -> dict:
    Base.metadata.create_all(engine)
    db = SessionLocal()
    sf = ingest_csv(db, filename="loan_tape.csv", content=(DATA / "loan_tape.csv").read_bytes(),
                    uploaded_by_id="u-operator", uploaded_by_role="data_operator")
    srv_count = 0
    if (DATA / "servicer_update.csv").exists():
        srv = ingest_servicer_csv(db, filename="servicer_update.csv",
                                  content=(DATA / "servicer_update.csv").read_bytes(),
                                  uploaded_by_id="u-operator", uploaded_by_role="data_operator")
        srv_count = srv["imported_count"]
    run = run_validation(db, source_file_id=sf["id"], actor_id="u-operator", actor_role="data_operator")

    total_loans = db.scalar(select(func.count()).select_from(Loan)) or 0
    attention = db.scalar(select(func.count()).select_from(Loan)
                          .where(Loan.normalization_status == "attention")) or 0
    raw_total = db.scalar(select(func.count()).select_from(RawRecord)) or 0
    raw_failed = db.scalar(select(func.count()).select_from(RawRecord)
                           .where(RawRecord.import_status == "failed")) or 0

    # per-field normalization failure/review tallies from provenance
    prov_status = Counter()
    field_issues = Counter()
    for loan in db.scalars(select(Loan)):
        for p in (loan.field_provenance or []):
            prov_status[p["status"]] += 1
            if p["status"] in ("failed", "review"):
                field_issues[p["field"]] += 1

    by_rule = dict(db.execute(
        select(LoanException.exception_type, func.count()).group_by(LoanException.exception_type)
    ).all())
    by_severity = dict(db.execute(
        select(LoanException.severity, func.count()).group_by(LoanException.severity)
    ).all())
    loans_with_ex = db.scalar(select(func.count(func.distinct(LoanException.loan_pk)))) or 0
    db.close()

    quality = round(100.0 * (total_loans - loans_with_ex) / total_loans, 1) if total_loans else None
    return {
        "raw_rows": raw_total,
        "raw_failed_rows": raw_failed,
        "loans_normalized": total_loans,
        "servicer_records": srv_count,
        "needs_attention_rows": attention,
        "provenance_status_counts": dict(prov_status),
        "fields_with_issues": dict(field_issues.most_common()),
        "exceptions_total": sum(by_rule.values()),
        "exceptions_by_rule": dict(sorted(by_rule.items())),
        "exceptions_by_severity": by_severity,
        "loans_with_open_exceptions": loans_with_ex,
        "data_quality_score_pct": quality,
        "ruleset_version": run["ruleset_version"],
        "issue_classes_detected": len(by_rule),
    }


def write_md(stats: dict):
    lines = [
        "# Dataset Quality Metrics (machine-derived)",
        "",
        "> Auto-generated by `scripts/data_quality_report.py`. Reproducible from the repository.",
        "",
        f"- Raw rows: **{stats['raw_rows']}** (failed import: {stats['raw_failed_rows']})",
        f"- Loans normalized: **{stats['loans_normalized']}** · servicer records: {stats['servicer_records']}",
        f"- Needs-attention (normalization): **{stats['needs_attention_rows']}**",
        f"- Provenance status counts: `{stats['provenance_status_counts']}`",
        f"- Exceptions total: **{stats['exceptions_total']}** across "
        f"**{stats['issue_classes_detected']}** classes (ruleset {stats['ruleset_version']})",
        f"- Exceptions by severity: `{stats['exceptions_by_severity']}`",
        f"- Loans with open exceptions: **{stats['loans_with_open_exceptions']}** · "
        f"data-quality score: **{stats['data_quality_score_pct']}%**",
        "",
        "## Exceptions by rule",
        "",
        "| rule | count |",
        "|---|---|",
    ]
    for rule, n in stats["exceptions_by_rule"].items():
        lines.append(f"| {rule} | {n} |")
    lines += ["", "## Fields with normalization issues", "", "| field | failed/review |", "|---|---|"]
    for field, n in stats["fields_with_issues"].items():
        lines.append(f"| {field} | {n} |")
    (REPO / "docs" / "dataset-quality-metrics.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    stats = build()
    write_md(stats)
    print(json.dumps(stats, indent=2))
    try:
        os.unlink(_tmp.name)
    except OSError:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
